### ISSUE TITLE
"Cut non-ASCII characters" dysfunctional

### ISSUE THREAD

**Issue by arestifo** [recursivepaws/Steg#3]
It is inconsistent and doesn't work.

**Comment by nicosogangstar** [comment]
boi i fixd dat

**Comment by a-re** [comment]
??????

**Comment by nicosogangstar** [comment]
What? I fixed it in the most recent commit.

On Wed, Feb 17, 2016 at 8:52 AM, Alex Restifo <notifications@github.com>
wrote:

> ??????
> On Feb 17, 2016 8:42 AM, "Nicolas Gonzalez" <notifications@github.com>
> wrote:
>
> > boi i fixd dat
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/nicosogangstar/Steg/issues/3#issuecomment-185208602
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nicosogangstar/Steg/issues/3#issuecomment-185211921>.
>



-- 
Nicolas Gonzalez

**Comment by nicosogangstar** [comment]
'Cut non-ASCII text' removed as feature. The endmarker feature makes this feature obsolete.
